[project]
name = "runtime_builder"
description = "Allow automatic builds in edit mode"
authors = [{name = "Richard Kiss", email = "him@richardkiss.com"}]
readme = "README.md"
version = "0.1.2"


[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
